name: CI for Last.fm with Friends

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/*'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/*'

  workflow_dispatch:

jobs:
  build:
    name: Pull, Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Pull new changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: cd /root/projects/lastfm-with-friends && git pull
            
      - name: npm install
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: cd /root/projects/lastfm-with-friends && npm i
            
      - name: ng build --prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: cd /root/projects/lastfm-with-friends && ng build --prod
            
      - name: Copy files to web root
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: \cp -a /root/projects/lastfm-with-friends/dist/lastfm-with-friends/. /usr/share/nginx/lastfm-with-friends/
          
      - name: Run buildjson.sh
        if: always()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: cd /root/projects/lastfm-with-friends && . /root/.scripts/buildjson.sh > /usr/share/nginx/lastfm-with-friends/assets/build.json
          
      - name: Restart Flask server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: service lastfm-with-friends restart
